version: "3.8"

services:
  app-dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app # Монтируем текущую директорию внутрь контейнера
      - /app/node_modules # Исключаем node_modules из монтирования
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  app-prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
