apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
